workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.techcorp.attendanceapp"
        GOOGLE_PLAY_TRACK: alpha
      node: 18
      npm: latest
      ndk: r21e
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Prebuild for Android
        script: |
          expo prebuild --platform android --clear
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - developer@techcorp.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.techcorp.attendanceapp
      vars:
        APP_STORE_APPLE_ID: 1555555551
      node: 18
      npm: latest
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request  
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Prebuild for iOS
        script: |
          expo prebuild --platform ios --clear
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/AttendanceApp.xcworkspace" --scheme "AttendanceApp"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - developer@techcorp.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
        submit_to_app_store: false